export const projects = [
  {
    id: 1,
    title: 'RAG-Based College Chatbot',
    subtitle: 'NIT Patna Assistant',
    description: 'An intelligent conversational chatbot for college students and faculty that answers questions grounded in college documents and live website data.',
    longDescription: 'Students can upload PDFs or paste any URL — the system crawls the website, extracts content, and answers questions with source citations. Faculty get a separate admin portal to manage documents, monitor usage, and control access. Built with a full RAG pipeline using vector search, cross-encoder reranking, and Llama 3.3 70B via Groq API.',
    tags: ['Python', 'FastAPI', 'LangChain', 'ChromaDB', 'PostgreSQL', 'Redis', 'Groq API', 'LLM'],
    color: '#00D9FF',
    accent: '#8B5CF6',
    icon: '🤖',
    category: 'AI / RAG',
    status: 'In Development',
    github: '#',
    live: null,
    features: [
      'PDF upload + URL crawling with Playwright',
      'Vector search with ChromaDB + Sentence Transformers',
      'Cross-Encoder reranking for accuracy',
      'Source citations with every answer',
      'Faculty admin portal with usage analytics',
      'JWT Authentication + Redis caching',
    ],
    tech: {
      'AI / NLP': ['LangChain', 'ChromaDB', 'Sentence Transformers', 'Cross-Encoder Reranker', 'Groq (Llama 3.3 70B)'],
      'Backend': ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Celery'],
      'Scraping': ['Playwright', 'playwright-stealth', 'BeautifulSoup'],
      'Auth': ['JWT Authentication'],
    },
  },
  {
    id: 2,
    title: 'Smart Hospital Finder',
    subtitle: 'Emergency Healthcare Platform',
    description: 'A full-stack web app that helps patients find nearby hospitals in real time, check live bed & ICU availability, and access one-tap emergency services.',
    longDescription: 'GPS-based routing to the 3 nearest emergency hospitals, real-time bed availability, doctor appointment booking, and integrated Razorpay payment. Built with Django REST Framework with a clean Tailwind CSS frontend and Google Maps integration.',
    tags: ['Python', 'Django', 'REST API', 'Google Maps', 'Razorpay', 'PostgreSQL'],
    color: '#FF4ECD',
    accent: '#8B5CF6',
    icon: '🏥',
    category: 'Full Stack',
    status: 'In Development',
    github: '#',
    live: null,
    features: [
      'Real-time hospital & ICU bed availability',
      'GPS-based routing to 3 nearest emergency hospitals',
      'Doctor appointment booking system',
      'One-tap emergency services',
      'Razorpay payment integration',
      'HTML5 Geolocation API',
    ],
    tech: {
      'Backend': ['Python', 'Django', 'Django REST Framework', 'SQLite / PostgreSQL'],
      'Frontend': ['Tailwind CSS', 'JavaScript', 'HTML5 Geolocation API'],
      'Integrations': ['Google Maps API', 'Razorpay', 'REST APIs'],
    },
  },
  {
    id: 3,
    title: 'AI Robot Path Planning',
    subtitle: 'Genetic Algorithm System',
    description: 'An interactive AI system that evolves optimal robot navigation paths through obstacle-filled grid environments using a Genetic Algorithm.',
    longDescription: 'The robot autonomously learns to navigate from start to goal by evolving thousands of candidate movement sequences across multiple generations — avoiding collisions, escaping dead ends, and minimizing path length — without any hardcoded pathfinding rules. Includes real-time visualization of the evolutionary process and fitness progression charting.',
    tags: ['Python', 'FastAPI', 'Genetic Algorithm', 'Canvas API', 'JavaScript'],
    color: '#8B5CF6',
    accent: '#00D9FF',
    icon: '🤖',
    category: 'AI / Algorithm',
    status: 'Completed',
    github: '#',
    live: null,
    features: [
      'Genetic Algorithm with tournament selection',
      'Two-point crossover + adaptive mutation',
      'Zone-based fitness function',
      'Real-time Canvas API visualization',
      'Fitness progression charting',
      'REST API backend with FastAPI',
    ],
    tech: {
      'AI / Algorithm': ['Genetic Algorithm', 'Tournament Selection', 'Two-Point Crossover', 'Adaptive Mutation'],
      'Backend': ['Python', 'FastAPI', 'Pydantic', 'Uvicorn'],
      'Frontend': ['HTML5', 'CSS3', 'JavaScript ES6+', 'Canvas API'],
    },
  },
];